config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'
	
  get    '/blog',    to: 'static_pages#blog'

  get    '/about',   to: 'static_pages#about'

  get    '/contact', to: 'static_pages#contact'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get    '/signup',  to: 'users#new'

  post   '/signup',  to: 'users#create'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit , :update] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if !@user.nil? %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_loginform.html.erb
<%= form_for(:session, url: login_path) do |f| %>
    <div class="form-group">
        <%= f.email_field :email, class: 'form-control input-lg', placeholder: 'Email' %>
    </div><!-- end form-group -->
    <div class="form-group">
        <%= f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
    </div><!-- end form-group -->
    <div class="form-group text-left">       
        <%= f.label :remember do %>
            <%= f.check_box :remember, id: 'remember', class: 'checkbox-input mb-10 mr-10 pull-left styled' %>
            <span>Remember me</span>
        <% end %>
        <label class="pull-right"><%= link_to "Forgot Password", new_password_reset_path %></label>
    </div><!-- end form-group -->
    <div class="form-group">
        <%=  f.submit "Log in", class: "btn btn-default btn-block round btn-lg" %>
    </div><!-- end form-group -->
<% end %>